# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bus2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-40, -20, 921, 561))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setTabletTracking(False)
        self.frame.setStyleSheet("background-color: rgb(39, 39, 45);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_2.setGeometry(QtCore.QRect(780, 50, 111, 381))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton = QtWidgets.QPushButton(self.page_6)
        self.pushButton.setGeometry(QtCore.QRect(10, 80, 61, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: Transparent;\n"
"    background-repeat:no-repeat;\n"
"    border: none;\n"
"    cursor:pointer;\n"
"    overflow: hidden;\n"
"    outline:none;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 200, 61, 61))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: Transparent;\n"
"    background-repeat:no-repeat;\n"
"    border: none;\n"
"    cursor:pointer;\n"
"    overflow: hidden;\n"
"    outline:none;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 140, 61, 61))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: Transparent;\n"
"    background-repeat:no-repeat;\n"
"    border: none;\n"
"    cursor:pointer;\n"
"    overflow: hidden;\n"
"    outline:none;\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 61, 61))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: Transparent;\n"
"    background-repeat:no-repeat;\n"
"    border: none;\n"
"    cursor:pointer;\n"
"    overflow: hidden;\n"
"    outline:none;\n"
"}")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.listWidget = QtWidgets.QListWidget(self.page_7)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 101, 261))
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listWidget.setStyleSheet("QListWidget{color:rgb(219,219,195);\n"
"background-color:rgb(76,76,81);\n"
"border:none;ve\n"
"font:8pt \"Trebuchet MS\";}\n"
"QListWidget::item:selected{background-color:#c68383;}\n"
"QListWIdget::hover{background:rgb(186,208,0);}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 300, 75, 23))
        self.pushButton_5.setStyleSheet("QPushButton{color:white;\n"
"    color: #dfdac2;\n"
"background-color: rgb(27, 29, 35);\n"
"border:none;\n"
"border-radius:8px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"background-color:#5a606b;}\n"
"QPushButton:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget_2.addWidget(self.page_7)
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(210, 400, 16, 16))
        self.label_30.setStyleSheet("color: rgb(219, 219, 195);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(80, 40, 671, 341))
        self.tabWidget.setStyleSheet("QTabWidget{background-color:rgb(219,219,195);\n"
"border:none;\n"
"\n"
"}\n"
"QTabWidget:pane{\n"
"}\n"
"QWidget{\n"
"background-color:rgb(219,219,195);\n"
"}\n"
"QTabBar::tab {\n"
"color:rgb(39,39,45);\n"
"  background: rgb(137, 137, 121); \n"
"  border:none;\n"
"font:8pt \"Myriad Pro\";\n"
"width:42px;\n"
"height:30px;\n"
" padding:5px;\n"
"} \n"
"QTabBar::tab:selected { \n"
"  background:rgb(219,219,195);\n"
"  margin-bottom: -1px; \n"
"}\n"
"QTabWidget::tab-bar {\n"
"  background: rgb(219,219,195); \n"
"   border: 1px solid gray;\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_1.setGeometry(QtCore.QRect(0, 0, 671, 301))
        self.tableWidget_1.setStyleSheet("QTableWidget {\n"
"\n"
"border:none;\n"
"backcground:red;\n"
" selection-background-color:rgb(137,137,121);}\n"
"\n"
"\n"
"QHeaderView:section{\n"
"font:8pt \"Trebuchet MS\";\n"
"color:rgb(39,39,45);\n"
"border: none;\n"
"\n"
"background-color: #c68383;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"height: 14px;\n"
"margin: 0px 21px 0 21px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: rgb(137, 137, 121);\n"
"min-width: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: right;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"subcontrol-position: left;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"width: 14px;\n"
"margin: 21px 0 21px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(137, 137, 121);\n"
"min-height: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"")
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(4)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(130, 320, 16, 16))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 701, 301))
        self.tableWidget_2.setStyleSheet("QTableWidget {\n"
"\n"
"border:none;\n"
"backcground:red;\n"
" selection-background-color:rgb(137,137,121);}\n"
"\n"
"\n"
"QHeaderView:section{\n"
"font:8pt \"Trebuchet MS\";\n"
"color:rgb(39,39,45);\n"
"border: none;\n"
"\n"
"background-color: #c68383;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"height: 14px;\n"
"margin: 0px 21px 0 21px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: rgb(137, 137, 121);\n"
"min-width: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: right;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"subcontrol-position: left;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"width: 14px;\n"
"margin: 21px 0 21px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(137, 137, 121);\n"
"min-height: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(130, 320, 16, 16))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 671, 301))
        self.tableWidget_3.setStyleSheet("QTableWidget {\n"
"\n"
"border:none;\n"
"backcground:red;\n"
" selection-background-color:rgb(137,137,121);}\n"
"\n"
"\n"
"QHeaderView:section{\n"
"font:8pt \"Trebuchet MS\";\n"
"color:rgb(39,39,45);\n"
"border: none;\n"
"\n"
"background-color: #c68383;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"height: 14px;\n"
"margin: 0px 21px 0 21px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: rgb(137, 137, 121);\n"
"min-width: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: right;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"subcontrol-position: left;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"width: 14px;\n"
"margin: 21px 0 21px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(137, 137, 121);\n"
"min-height: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 47, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 671, 301))
        self.tableWidget_4.setStatusTip("")
        self.tableWidget_4.setStyleSheet("QTableWidget {\n"
"\n"
"border:none;\n"
"backcground:red;\n"
" selection-background-color:rgb(137,137,121);}\n"
"\n"
"\n"
"QHeaderView:section{\n"
"font:8pt \"Trebuchet MS\";\n"
"color:rgb(39,39,45);\n"
"border: none;\n"
"\n"
"background-color: #c68383;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"height: 14px;\n"
"margin: 0px 21px 0 21px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: rgb(137, 137, 121);\n"
"min-width: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: right;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"subcontrol-position: left;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"width: 14px;\n"
"margin: 21px 0 21px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(137, 137, 121);\n"
"min-height: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(8)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 671, 301))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"\n"
"border:none;\n"
"backcground:red;\n"
" selection-background-color:rgb(137,137,121);}\n"
"\n"
"\n"
"QHeaderView:section{\n"
"font:8pt \"Trebuchet MS\";\n"
"color:rgb(39,39,45);\n"
"border: none;\n"
"\n"
"background-color: #c68383;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"height: 14px;\n"
"margin: 0px 21px 0 21px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: rgb(137, 137, 121);\n"
"min-width: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: right;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"subcontrol-position: left;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"width: 14px;\n"
"margin: 21px 0 21px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(137, 137, 121);\n"
"min-height: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setGeometry(QtCore.QRect(131, 320, 16, 16))
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 18))
        self.menubar.setStyleSheet("QMenuBar {\n"
"color:rgb(219, 219, 195);\n"
"    background-color :rgb(76,76,81);\n"
"    spacing: 5px; /* spacing between menu bar items */\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
"    background:#8d8a84;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background:#8d8a84;\n"
"}\n"
"QMenu {\n"
"color:rgb(219, 219, 195);\n"
"    background-color :rgb(76,76,81);\n"
"    margin: 2px; /* some spacing around the menu */\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 2px 25px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    border-color:#8d8a84;\n"
"    background:#8d8a84;\n"
"}\n"
"\n"
"QMenu::icon:checked { /* appearance of a \'checked\' icon */\n"
"    background: gray;\n"
"    border: 1px inset gray;\n"
"    position: absolute;\n"
"    top: 1px;\n"
"    right: 1px;\n"
"    bottom: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: rgb(219, 219, 195);\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.actiond = QtWidgets.QAction(MainWindow)
        self.actiond.setObjectName("actiond")
        self.actiond_2 = QtWidgets.QAction(MainWindow)
        self.actiond_2.setObjectName("actiond_2")
        self.actiond_3 = QtWidgets.QAction(MainWindow)
        self.actiond_3.setObjectName("actiond_3")
        self.menu.addAction(self.action_7)
        self.menu.addAction(self.action_8)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_6)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Работа с базой данных"))
        self.pushButton.setToolTip(_translate("MainWindow", "Добавить запись"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Редактировать запись"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "Обновить"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Запрос 1 "))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести машины, у которых количество мест больше введенного пользователем параметра. </p></body></html>"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Запрос 2"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести водителей, стаж которых больше введенного пользователем параметра. </p></body></html>"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Запрос 3"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести все номера рейсов за определенную дату. </p></body></html>"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Запрос 4 "))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести машины , у которых марка = определенная марка. </p></body></html>"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Запрос 5"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести ФИО водителей, которые совершили рейс за определенную дату. </p></body></html>"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Запрос 6"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести ФИО водителя, который совершал рейс по определенному маршруту. </p></body></html>"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Запрос 7"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести код маршрута, расстояние которого больше определенного расстояния. </p></body></html>"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "Запрос 8"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Сколько рейсов было совершено в определенную дату ?</p></body></html>"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "Запрос 9"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Сколько машин, у которых расход топлива больше определенного количества? </p></body></html>"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "Запрос 10"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести номера рейсов, цена билета которых больше определенной цены? </p></body></html>"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "Запрос 11"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести запись по номеру водителя в таблице «Водитель». </p></body></html>"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "Запрос 12"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести запись по коду машины в таблице «Автомашины». </p></body></html>"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "Запрос 13"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести запись по коду маршрута в таблице «Маршрут». </p></body></html>"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "Запрос 14"))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Вывести запись по номеру рейса в таблице  «Рейс». </p></body></html>"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_5.setText(_translate("MainWindow", "Ок"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "НомерВодителя"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ДатаРождения"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "СтажРаботы"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "КодМашины"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "МаркаМашины"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ЧислоМест"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "РасходТоплива"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "КодМаршрута"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ПунктОтправления"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ПунктНазначения"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Расстояние"))
        self.tableWidget_4.setToolTip(_translate("MainWindow", "hrrrrrr"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "НомерРейса"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "КодМаршрута"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "НомерВодителя"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "КодМашины"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ВремяОтправления"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ВремяПрибытия"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ЦенаБилета"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Запросы"))
        self.menu.setTitle(_translate("MainWindow", "Режим"))
        self.menu_2.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Пользователь"))
        self.action_2.setText(_translate("MainWindow", "Администратор"))
        self.action_3.setText(_translate("MainWindow", "Инструкция к программе"))
        self.action_4.setText(_translate("MainWindow", "Об авторе"))
        self.action_6.setText(_translate("MainWindow", "Выход"))
        self.action_7.setText(_translate("MainWindow", "Пользователь"))
        self.action_8.setText(_translate("MainWindow", "Администратор"))
        self.action_9.setText(_translate("MainWindow", "Печать"))
        self.actiond.setText(_translate("MainWindow", "Exel"))
        self.actiond_2.setText(_translate("MainWindow", "Word"))
        self.actiond_3.setText(_translate("MainWindow", "Блакнот"))
