# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogmarshrut.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Marshrut(object):
    def setupUi(self, Dialog_Marshrut):
        Dialog_Marshrut.setObjectName("Dialog_Marshrut")
        Dialog_Marshrut.resize(520, 100)
        self.frame = QtWidgets.QFrame(Dialog_Marshrut)
        self.frame.setGeometry(QtCore.QRect(0, 0, 521, 101))
        self.frame.setStyleSheet("background-color:rgb(219, 219, 195);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(430, 10, 71, 21))
        self.label_2.setStyleSheet("color:rgb(76,76,81);\n"
"font:8pt \"Trebuchet MS\";")
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame)
        self.spinBox_2.setGeometry(QtCore.QRect(440, 40, 42, 22))
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"color:white;\n"
"background-color: rgb(137, 137, 121);\n"
" border:none;\n"
"\n"
"}\n"
"")
        self.spinBox_2.setObjectName("spinBox_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 411, 51))
        self.tableWidget_2.setStyleSheet("QTableWidget {\n"
"\n"
"background-color:rgb(219, 219, 195);\n"
"\n"
"\n"
"border:none;\n"
"backcground:red;\n"
" selection-background-color:rgb(137,137,121);}\n"
"\n"
"\n"
"QHeaderView:section{\n"
"font:8pt \"Trebuchet MS\";\n"
"color:rgb(39,39,45);\n"
"border: none;\n"
"\n"
"background-color: #c68383;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"height: 14px;\n"
"margin: 0px 21px 0 21px;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: rgb(137, 137, 121);\n"
"min-width: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: right;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"border: none;\n"
"background: rgb(76, 76,81);\n"
"width: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"subcontrol-position: left;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: rgb(76, 76, 81);\n"
"width: 14px;\n"
"margin: 21px 0 21px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(137, 137, 121);\n"
"min-height: 25px;\n"
"border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"border: none;\n"
"background: rgb(55, 63, 77);\n"
"height: 20px;\n"
"border-top-left-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QHeaderView{\n"
"background-color:rgb(219, 219, 195);;\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Marshrut)
        self.buttonBox.setGeometry(QtCore.QRect(-10, 60, 341, 32))
        self.buttonBox.setStyleSheet("QPushButton{color:white;\n"
"    color: #dfdac2;\n"
"background-color: rgb(137, 137, 121);\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"background-color:#5a606b;}\n"
"QPushButton:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog_Marshrut)
        self.buttonBox.accepted.connect(Dialog_Marshrut.accept)
        self.buttonBox.rejected.connect(Dialog_Marshrut.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Marshrut)

    def retranslateUi(self, Dialog_Marshrut):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Marshrut.setWindowTitle(_translate("Dialog_Marshrut", "Добавить/Изменить"))
        self.label_2.setText(_translate("Dialog_Marshrut", "Номер записи"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_Marshrut", "КодМаршрута"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_Marshrut", "Отправление"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_Marshrut", "Назначения"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_Marshrut", "Расстояние"))
