# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogr.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_r(object):
    def setupUi(self, Dialog_r):
        Dialog_r.setObjectName("Dialog_r")
        Dialog_r.resize(396, 215)
        self.frame = QtWidgets.QFrame(Dialog_r)
        self.frame.setGeometry(QtCore.QRect(0, -1, 401, 301))
        self.frame.setStyleSheet("background-color: rgb(39, 39, 45);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 101, 23))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{color:rgb(219,219,195);\n"
"background:rgb(76,76,81);\n"
"border:none;\n"
"border-radius: 9px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 110, 101, 23))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{color:rgb(219,219,195);\n"
"background:rgb(76,76,81);\n"
"border:none;\n"
"border-radius: 9px;}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog_r)
        QtCore.QMetaObject.connectSlotsByName(Dialog_r)

    def retranslateUi(self, Dialog_r):
        _translate = QtCore.QCoreApplication.translate
        Dialog_r.setWindowTitle(_translate("Dialog_r", "Выберите режим"))
        self.pushButton.setText(_translate("Dialog_r", "Администратор"))
        self.pushButton_2.setText(_translate("Dialog_r", "Пользователь"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_r = QtWidgets.QDialog()
    ui = Ui_Dialog_r()
    ui.setupUi(Dialog_r)
    Dialog_r.show()
    sys.exit(app.exec_())
